---
functional:
  - Пользователь может играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Пользователь может решать задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - Пользователь может выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Пользователь может выбрать задачи на двух языках русском и английском 
  - Пользователь может писать в игравой чат, в котором общаются зарегистрированные пользователи
  - Пользователь может просматривать завершенную игру в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователь получает очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность подключить подписку Premium 
